### ISSUE TITLE
Deletation bug for *remindme

### ISSUE THREAD

**Issue by LafuenteAstronomy** [UtopicUnicorns/artemis#1]
I deleted a *remindme for a bump, so that I can bump at a later time to retain at least 30 minutes bump cooldown between both servers:
![image](https://user-images.githubusercontent.com/56778509/81626744-2a2a2400-942f-11ea-98d3-137a16249bbd.png)
![image](https://user-images.githubusercontent.com/56778509/81626827-5f367680-942f-11ea-8575-bd3e612101be.png)
But the remindeme was actually still there despite that, and as a result, the reminder was still given:
![image](https://user-images.githubusercontent.com/56778509/81626787-48901f80-942f-11ea-8a3a-a8cd2453adb7.png)

**Comment by UtopicUnicorns** [comment]
That reminder belonged to gfg... not to you

**Comment by UtopicUnicorns** [comment]
Found an issue with how guild/channel names are displayed which may cause confusion.
Please open a new issue when I have not fixed that in an hour
