### ISSUE TITLE
Photos do not show at original sizes anymore

### ISSUE THREAD

**Issue by LafuenteAstronomy** [UtopicUnicorns/artemis#2]
Hello!

I noticed that when right-clicking the photos in the LeaderBoard section,
![image](https://user-images.githubusercontent.com/56778509/82438430-a1b12080-9acb-11ea-9bfb-cea5e446b23e.png)
 they all show the same size(128X128)
![image](https://user-images.githubusercontent.com/56778509/82438396-90681400-9acb-11ea-8146-65aaf983542a.png)
![image](https://user-images.githubusercontent.com/56778509/82438408-978f2200-9acb-11ea-8d23-98dbb3001ca6.png)

. Each of them used to show different sizes, usually larger sizes. If any, can the overall sizes of the photos be at least increased so that they are large enough and thus, have good quality? That way, I can save them and use them for making emojis based on their profiles of members. I find this method honestly better than pinging them through Dyno's ?avatar command. 

Thanks in advance

**Comment by UtopicUnicorns** [comment]
Will see if the current discord api accepts this

**Comment by UtopicUnicorns** [comment]
Should be fixed now, check if this is the case.

**Comment by LafuenteAstronomy** [comment]
It works now, thanks
