### ISSUE TITLE
Word triggered point give event toggle

### ISSUE THREAD

**Issue by Anthony-B-Russo10** [UtopicUnicorns/artemis#21]
Basically what is needed is a section on Artemis' website or a command to enable/disable the word triggered point give events, particularly the one triggered by welcome.

**Comment by UtopicUnicorns** [comment]
Will change how it works by requirering a mention in that channel.

**Comment by Anthony-B-Russo10** [comment]
Ok, since that will help cut down the spam cause by it.

**Comment by UtopicUnicorns** [comment]
Yeah, the welcoming thing only works inside of the channel where the welcome images are, and I kinda want this to become a core feature for Artemis so people socialize and welcome each other more, give me a second will change it in a moment.

**Comment by Anthony-B-Russo10** [comment]
Alright

**Comment by UtopicUnicorns** [comment]
Alright it has been changed, give it a test spin.
Try welcoming without mentioning the user and welcoming with mentioning the user

**Comment by Anthony-B-Russo10** [comment]
It works

**Comment by UtopicUnicorns** [comment]
Alright pushing a changelog in the Artemis core server
