### ISSUE TITLE
Smart Bot Module toggle 

### ISSUE THREAD

**Issue by Anthony-B-Russo10** [UtopicUnicorns/artemis#23]
There needs to be a way either via command or website to toggle the Smart Bot Module on or off.

**Comment by UtopicUnicorns** [comment]
I assume you mean the responses the bot gives when you start a sentence with `Artemis`?

**Comment by Anthony-B-Russo10** [comment]
Yes.

**Comment by UtopicUnicorns** [comment]
Would the term `Artemis Replies` be a better module name?

**Comment by Anthony-B-Russo10** [comment]
Yeah, can help prevent spam.

**Comment by UtopicUnicorns** [comment]
Alright added a toggle to the website called `Artemis Replies`.
It will be on by default, but you can just turn it off
