### ISSUE TITLE
Automod not allowing images in any channel.

### ISSUE THREAD

**Issue by Anthony-B-Russo10** [UtopicUnicorns/artemis#25]
Artemis' automod feature is not allowing user pings, images to be sent, allowing gif embeds, emojis, or punctuation characters (like !@#$%^&*()_+,./;') to be sent in any channel if they are below the bot role. When automod is turned off users can send images but with it on it does as described above.

The last time users were able to send images in the general channel was before I kicked the Censor Bot.

**Comment by UtopicUnicorns** [comment]
Was a faulthy entry in the wordlist filter. not sure how that even happened as that should be impossible, but here we are.
I will continue to monitor.
Gif embeds are not Artemis's mistake btw that seems a perm problem
