### ISSUE TITLE
Is the API error a bug?

### ISSUE THREAD

**Issue by Anthony-B-Russo10** [UtopicUnicorns/artemis#3]
When ever the !approve command is used to force approve a user, Artemis approves a user and gives out an api error as well. Is that a bug in the bot or Discord's own API?

![2020-06-03 (3)](https://user-images.githubusercontent.com/57239744/83714128-e96d9700-a5f7-11ea-9176-1a20305ab2a0.png)

**Comment by UtopicUnicorns** [comment]
Will fix in a moment

**Comment by Anthony-B-Russo10** [comment]
Ok, thanks.

**Comment by UtopicUnicorns** [comment]
The user did get approved properly right?

**Comment by Anthony-B-Russo10** [comment]
Yes they do.

**Comment by UtopicUnicorns** [comment]
fixed
