### ISSUE TITLE
Sometimes, board command will not show top 10 members if someone from the list is banned

### ISSUE THREAD

**Issue by LafuenteAstronomy** [UtopicUnicorns/artemis#5]
![image](https://user-images.githubusercontent.com/56778509/84581997-ee60f080-ae18-11ea-8fc9-30a180c7fa8c.png)

This is the board from one of the servers I'm in. It only shows the top 8 members, and not the to 10 because 2 people who made it to the top 10 were banned. Is there a way to fix it so that the 2 members below the 8th place can be featured, and thus, return back to the Top Ten? Thanks

**Comment by LafuenteAstronomy** [comment]
![image](https://user-images.githubusercontent.com/56778509/84582017-29fbba80-ae19-11ea-9fa4-66a9905fe29f.png)

More proof, just in case you think I might be lying or dealing with a non-issue

**Comment by UtopicUnicorns** [comment]
Fixed and done, thanks for opening the issue
