### ISSUE TITLE
Words in the wordlist dont get filtered when they have effects or dots on then

### ISSUE THREAD

**Issue by GurrenLagannTSS** [UtopicUnicorns/artemis#6]
Apparently, the bot cant remove messages in the wordlist if they have other characters next to then:
![Screenshot_20200627-204006](https://user-images.githubusercontent.com/54154710/85934245-d2e4f380-b8b6-11ea-9fa2-e254737aedf3.png)
Some effects i saw that broke the filtering:
Bold
Italic
Bold + Italic
Spoilers
Dots next to the word...

Alternating letters (caps and not caps) get filtered though.

**Comment by UtopicUnicorns** [comment]
Can you check if it's fixed now, looks like I made an oopsie

**Comment by GurrenLagannTSS** [comment]
Its working again, thanks!

**Comment by UtopicUnicorns** [comment]
Could you deep try again?
