### ISSUE TITLE
Leaderboard doesn't display special characters

### ISSUE THREAD

**Issue by SevenSpheres** [UtopicUnicorns/artemis#7]
**Describe the bug**
The leaderboard on the Artemis website doesn't display spaces, underscores, hyphens, or non-ASCII characters in usernames.

**To Reproduce**
Just look at the leaderboard for any server Artemis is on.

**Screenshot as an example:**
Several of these usernames should have spaces/underscores/hyphens, although the worst one is "dɹǝᗡ snɯuᴉꟽ ǝɥꓕ" which is displayed as just "dsnu".
![leaderboardbug](https://user-images.githubusercontent.com/56284207/86173151-c3df8a80-badc-11ea-9d29-822cc01f6edf.png)

**Comment by UtopicUnicorns** [comment]
This is intentional, as some users were managing to inject alerts into their names by using <script>.
I will check if I can adjust the filter to be a bit more lax

**Comment by UtopicUnicorns** [comment]
Fixed
